baseURL = 'https://majoh.com'
languageCode = 'en-us'
title = 'majoh.com'

[[module.imports]]
    path = 'github.com/spf13/hyde'

theme = ["github.com/spf13/hyde"]

[params]
  themeColor = "theme-base-0d"
  description = 'Photography minus the phone'

[params.meta]
    favicon = true
    faviconVersion = "3"

[menu]
  [[menu.main]]
    name = "Disclosure"
    url = "/affiliate-disclosure/"
  [[menu.main]]
    name = "Archives"
    url = "/archives.html"

mainSections = ["posts"] # list any other content types to include

[build.environment]
  HUGO_VERSION = "0.151.0"
