baseURL = 'https://majoh.netlify.app'
languageCode = 'en-us'
title = 'majoh.com'

[[module.imports]]
    path = 'github.com/spf13/hyde'

theme = 'hyde'

[params]
  themeColor = "theme-base-0d"
  description = 'Film photography (and sometimes digital)'

[build.environment]
  HUGO_VERSION = "0.151.0"

